CREATE TABLE IF NOT EXISTS "UserGroup" (
  "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "UpdatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "UserId" INTEGER REFERENCES "Users" ("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  "GroupId" INTEGER REFERENCES "Groups" ("Id") ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY ("UserId","GroupId")
);


CREATE TABLE Users (
  "Id"        serial,
  "Login"     VARCHAR(64) NOT NULL,
  "Password"  VARCHAR(64) NOT NULL,
  "Age" INTEGER,
  "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "UpdatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("Id")
);

CREATE TABLE Groups (
  "Id"        serial,
  "Name"     VARCHAR(64) NOT NULL,
  "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "UpdatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("Id")
);

